# Generated by Django 3.2.4 on 2021-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itstep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='photo'),
        ),
    ]
