# Generated by Django 3.2.4 on 2021-06-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itstep', '0003_rename_cat_id_exercises_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itstep.category'),
        ),
    ]
